# Generated by Django 4.2.1 on 2023-06-17 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_holiday_slot_attendance_periods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="periods",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ]
            ),
        ),
    ]
