# Generated by Django 4.1 on 2023-06-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date", "periods")},
        ),
    ]
